human-readable=false
file-allocation=none
seed-time=0
bt-enable-lpd=true
summary-interval=0
truncate-console-readout=false
enable-color=false
check-integrity=true
bt-max-peers=150
bt-max-open-files=1024
min-tls-version=TLSv1.2
bt-tracker-connect-timeout=30
disk-cache=64M
dht-entry-point=router.bittorrent.com:6881
dht-entry-point6=router.bittorrent.com:6881
bt-save-metadata=true
peer-id-prefix=-7LAR-
max-connection-per-server=16
split=64
min-split-size=1M
uri-selector=adaptive
lowest-speed-limit=50K
max-tries=5
retry-wait=3
connect-timeout=10
timeout=30
bt-request-peer-speed-limit=100K